on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  test-intermediates:
    runs-on: ubuntu-latest
    container: inseefrlab/onyxia-rstudio
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Test intermediate scripts
        run: |
          Rscript -e "renv::restore()"
          SCRIPT_DIR="intermediates"
          for script in "$SCRIPT_DIR"/*.R; do
            echo "---------- Running $script"
            Rscript "$script"
          done
  build-deploy:
    runs-on: ubuntu-latest
    container: inseefrlab/onyxia-rstudio
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Configure safe.directory  # Workaround for actions/checkout#760
        run: git config --global --add safe.directory /__w/funathon2024_sujet2/funathon2024_sujet2
      - name: Render website
        run: |
          Rscript -e "renv::restore()"
          quarto render --to html
      - name: Publish to Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email quarto-github-actions-publish@example.com
          git config --global user.name "Quarto GHA Workflow Runner"
          quarto publish gh-pages . --no-render --no-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}